version: "3.7"

volumes:
    vue-cli-node-volume: 

services:
    web:
        build:
            context: ./docker/web
        container_name: web
        ports:
            - "8080:8080"
        volumes:
            - ./web:/app/
            - vue-cli-node-volume:/app/node_modules
        tty: true

    node:
        build:
            context: ./docker/node
        container_name: node_practice
        ports:
            - "3000:3000"
        volumes:
            - ./node:/app/
            - vue-cli-node-volume:/app/node_modules
        tty: true
        
